name: SlapPlayers
main: nl.stoux.SlapPlayers.SlapPlayers
authors: [Stoux2]
version: 2.0.2
description: A core plugin for SlapHomebrew plugins. This plugin keeps track of all player names and their UUIDs.