name: SlapPlayers
main: nl.stoux.SlapPlayers.SlapPlayers
authors: [Stoux2]
version: 1.0.0
description: A core plugin for SlapHomebrew plugins. This plugin keeps track of all player names and their UUIDs.